---
title: "Examen - Lección 1"
author: "Julio Cesar Contreras Huerta"
date: "10/5/2020"
output: pdf_document
---
# 1. Cargamos las librerías a utilizar


```{r eval = TRUE, message=FALSE}
library(raster)
library(sf)
library(rgdal)
```

# 2. Cargamos las bandas
```{r include=TRUE}
list_names <-list.files("T/Data/Land", 
                        pattern="*B[1234567]\\.TIF$", # Patron para localizar las bandas de 1 al 7
                        all.files = T,
                        recursive = T,
                        full.names = T)
landsat8 <- stack(list_names)
```

# 3. Visualizacion RGB
## 3.1 Falso color
```{r echo=TRUE, fig.width = 2.5, fig.height = 2.5, fig.align="center"}
plotRGB(landsat8, 5,4,3, stretch="lin") 
```

## 3.2 Color natural
```{r echo=TRUE, fig.width = 2.5, fig.height = 2.5, fig.align="center"}
plotRGB(landsat8, 3,2,1, stretch="hist") 
```

# 4. Recorte
```{r include=TRUE, results="hide", message=FALSE, warning=FALSE, cache=FALSE}
San_Cristobal <- st_read("T/Data/San_Cristobal.shp") # Distrito de San Cristobal-Lucanas 
San_Cristobal <- st_transform(San_Cristobal, crs(landsat8)) # Reproyección
```
## 4.1 Crop

```{r include=TRUE, results="hide", message=FALSE, warning=FALSE, cache=FALSE}
SCristobal_crop <- crop(landsat8, extent(San_Cristobal))
```

```{r eval=TRUE, echo=FALSE, message=FALSE, fig.width = 3.4}
plotRGB(landsat8, 3,2,1, stretch="hist")
plot(st_geometry(San_Cristobal), add = T, col = "red", border = "red")
```
```{r eval=TRUE, echo=FALSE, message=FALSE, fig.width = 2.7}
plotRGB(SCristobal_crop, 3,2,1, stretch="hist")
plot(st_geometry(San_Cristobal), add = T, border = "red", lwd = 5)
```

## 4.2 Mask
```{r include=TRUE, results="hide", message=FALSE, warning=FALSE, cache=FALSE}
SCristobal_mask <- mask(SCristobal_crop , San_Cristobal, updatevalue = NA)
```

```{r eval=TRUE, echo=FALSE, message=FALSE, fig.width = 3.4}
plotRGB(landsat8, 3,2,1, stretch="hist")
plot(st_geometry(San_Cristobal), add = T, col = "red", border = "red")
```
```{r eval=TRUE, echo=FALSE, message=FALSE, fig.width = 2.7}
plotRGB(SCristobal_mask, 3,2,1, stretch="hist")
```


# 5. Índices espectrales y reproyección a WGS84
## 5.1 NDVI
```{r include=TRUE, results="hide", message=FALSE, warning=FALSE, cache=FALSE}
red <- landsat8[[3]]# red
nir <- landsat8[[4]] # nir
ndvi <- (nir - red)/(nir + red) # NDVI
ndvi_wgs84 <- projectRaster(ndvi, crs=CRS("+init=epsg:4326"), method = "bilinear")
```
```{r echo=TRUE, fig.width = 7, fig.height = 7, fig.align="center"}
plot(ndvi_wgs84, main = "NDVI WGS84")
```


## 5.1 NDWI
```{r include=TRUE, results="hide", message=FALSE, warning=FALSE, cache=FALSE}
nir <- landsat8[[4]]# nir
green <- landsat8[[2]] # green
ndwi <- (green - nir)/(green + nir) # NDWI
ndwi_wgs84 <- projectRaster(ndwi, crs=CRS("+init=epsg:4326"), method = "bilinear")
```
```{r echo=TRUE, fig.width = 7, fig.height = 7, fig.align="center"}
plot(ndwi_wgs84, main = "NDWI WGS84 ")
```

